create table inquerys (
id BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
mailAddress VARCHAR(50) NOT NULl,
name VARCHAR(30) NOT NULl,
old VARCHAR(3) NOT NULL,
address VARCHAR(200) NOT NULL,
classification VARCHAR(3) NOT NULL,
day VARCHAR(50) NOT NULL,
unread VARCHAR(1)NOT NULL,
body VARCHAR(1000) NOT NULL
);

CREATE TABLE users (
    username VARCHAR(50) NOT NULL,
    password VARCHAR(500) NOT NULL,
    authority ENUM('ADMIN', 'USER') NOT NULL
    delete_flag BOOLEAN DEFAULT FALSE NOT NULL
);